[build]
environment = { PYTHON_VERSION = "3.13" }
# command = "bash ./build.sh"
command = "poetry install --no-dev && poetry run poe doc"
publish = "docs/_build/html"

[build.environment]
PYTHON_VERSION = "3.13"

[[redirects]]
from = "/"
to = "/ja/"
status = 301
