[build]
environment = { PYTHON_VERSION = "3.13" }
command = "poetry install --no-root && poetry show && poetry run poe doc"
publish = "docs/_build/html"

[[redirects]]
from = "/"
to = "/ja/"
status = 302
conditions = { Language = ["ja"] }
force = true

[[redirects]]
from = "/"
to = "/en/"
status = 302
force = true
