[build]
environment = { PYTHON_VERSION = "3.13" }
# command = "bash ./build.sh"
command = "poetry install && poetry run poe doc"
publish = "docs/_build/html"

[[redirects]]
from = "/"
to = "/ja/"
status = 301
