[build]
command = "poetry install --no-root && env | sort && poetry show && poetry run doit doc"
publish = "docs/_build/html"

[build.environment]
PYTHON_VERSION = "3.13"
LANG = "ja_JP.UTF-8"
LANGUAGE = "ja_JP:ja"
LC_ALL = "ja_JP.UTF-8"
TZ = "Asia/Tokyo"

[[redirects]]
from = "/"
to = "/ja/"
status = 302
conditions = {Language = ["ja"]}
force = true

[[redirects]]
from = "/"
to = "/en/"
status = 302
force = true
