[build]
publish = "docs/_build/html"
# command = "bash ./build.sh"
command = "poetry install --no-dev && poetry run poe doc"
environment = { PYTHON_VERSION = "3.13" }

[[redirects]]
from = "/"
to = "/ja/"
status = 301
