[build]
environment = { PYTHON_VERSION = "3.13" }
command = "poetry install --no-root && poetry run poe doc"
publish = "docs/_build/html"

[[redirects]]
from = "/"
to = "/ja/"
status = 302
conditions = { Language = ["ja"] }

# fallback: その他の言語は英語へ
[[redirects]]
from = "/"
to = "/en/"
status = 302
