# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

project = 'mtakagishi'
copyright = '2025, mtakagishi'
author = 'mtakagishi'

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%Y-%m-%d %H:%M:%S'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'myst_parser',  # For Markdown support
    # 'sphinxcontrib.blockdiag',
    'sphinx_sitemap',
    'sphinxnotes.strike',
    'sphinx_last_updated_by_git',
    'sphinx_git',
    'ablog',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ja'

# Sphinx document translation with sphinx gettext feature uses these settings:
locale_dirs = ['locale/']
gettext_compact = False

html_context = {
    'support_languages': {
        'ja': '日本語',
        'en': 'English',
        # 'zh': '中文',
        # 'es': 'español',
        # 'fr': 'Français',
        # 'hi': 'हिन्दी',
    }
}


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_title = project
html_theme = 'pydata_sphinx_theme'
html_static_path = ['_static']
html_logo = "_static/logo.png"
html_favicon = "_static/favicon.ico"
html_theme_options = {
    "logo": {
        "text": project,
    },
    "icon_links": [
        {
            "name": "X",
            "url": "https://x.com/mtakagishi_note",
            "icon": "fa-brands fa-x-twitter",
        },
        {
            "name": "GitHub",
            "url": "https://github.com/mtakagishi/note",
            "icon": "fa-brands fa-github",
        },
    ],
    "navbar_end": ["navbar-icon-links", "language_swicher.html"],
    "article_footer_items": ["ads_google.html","ads_themoneytizer.html"],
    "footer_start": ["copyright", "last-updated.html"],
    "footer_end": ["sphinx-version", "theme-version"],
    # https://ablog.readthedocs.io/en/stable/manual/templates-themes.html#blog-sidebars
    "secondary_sidebar_items": {
      "**": [
        "ablog/recentposts.html",
        "ablog/tagcloud.html",
        "ablog/categories.html",
        "ablog/archives.html",
      ],
    },
}
html_theme_options["analytics"] = {
    "google_analytics_id": "G-ZQ74H2ZF8F",
}

html_sidebars = {
    "posts/index": [],
}

[extensions]
todo_include_todos = True

source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'markdown',
    '.md': 'markdown',
}
# sphinx-sitemap
html_baseurl = 'https://mtakagishi.com/'
# html_extra_path = ['robots.txt', 'ads.txt']

# blockdiag
# blockdiag_html_image_format = 'SVG'
# blockdiag_fontpath = 'docs/_font/ipaexg.ttf'

# ablog
# 必須設定（カスタマイズ可能）
blog_path = "blog"
fontawesome_included = True  # 必要ならアイコン表示に使用
post_redirect_refresh = 1
datetime_format = '%Y-%m-%d'
post_date_format = '%Y-%m-%d'
post_date_format_short = '%m-%d'